# Multitask

Recognizing variety -> recognizing disease

We were given variety, but did not it for training because we only had to predict disease. However, using variety to predict it may also give us a better result. 

TODO:

- Use bigger images for training.
- Try using different crop/squish after different batches.
- Why does it take such a long time to go onto the next epoch? It seems like it takes about 10 seconds. Maybe because I was using too big of a batch size?   -> Restarting the instance fixed this issue..
- 

Interesting find:

- When training on bigger size, the model struggled on the second epoch. This also happened to Jeremy as well. I thought it happened because I increased the image too much. But it happened even after lowering the gap. May have to use smaller learning rate.

In [2]:
from fastai.vision.all import *
from fastcore.parallel import *
path = Path()
trn_path = path/'train_images'

In [3]:
df = pd.read_csv('train.csv')
df.head()

image_id                  label variety  age
0  100330.jpg  bacterial_leaf_blight   ADT45   45
1  100365.jpg  bacterial_leaf_blight   ADT45   45
2  100382.jpg  bacterial_leaf_blight   ADT45   45
3  100632.jpg  bacterial_leaf_blight   ADT45   45
4  101918.jpg  bacterial_leaf_blight   ADT45   45

Turning DataLoaders into DataBlocks. We need to return 2 outputs, variety and disease.

In [4]:
arch = resnet18

In [5]:
img2variety = { r.image_id:r.variety for _,r in df.iterrows() }

In [6]:
def get_variety(p):
    "Turn path into image name"
    return img2variety[p.name]

## Customizing head

Instead of creating a new head, we can just tell our neural net to output 20 numbers instead of 10, first 10 for disease and last 10 for the variety. The neural net will figure out how to minimize the loss by itself.

In [7]:
orig_lf = CrossEntropyLossFlat()

def disease_err(inp,disease,variety): return error_rate(inp[:,:10],disease)
def variety_err(inp,disease,variety): return error_rate(inp[:,10:],variety)
def disease_loss(inp,disease,variety): return orig_lf(inp[:,:10],disease)
def variety_loss(inp,disease,variety): return orig_lf(inp[:,10:],variety)
def loss(pred,disease,variety): return orig_lf(pred[:,:10],disease)+orig_lf(pred[:,10:],variety)
err_metrics = (disease_err,variety_err)
all_metrics = err_metrics+(disease_loss,variety_loss)

In [13]:
def get_dls(img_sizes):
    """Return the dataloaders"""
    for size in img_sizes:
        print('*' * 40)
        print(f'Size: {size}'.center(40, '*'))
        print('*' * 40)
        dblock = DataBlock(
            blocks=(ImageBlock, CategoryBlock, CategoryBlock),
            n_inp=1,                                             
            get_items=get_image_files,
            get_y=[parent_label, get_variety],
            splitter=RandomSplitter(seed=42),
            item_tfms=Resize(224, method='squish'),                
            batch_tfms=aug_transforms(size=size),
        )
        dls = dblock.dataloaders(trn_path, bs=64)
        yield dls

In [14]:
def prog_sizing(img_sizes, epochs=1):
    """Progressively use bigger images for training."""
    dls_gen = get_dls(img_sizes)
    dls = next(dls_gen)
    learn = vision_learner(dls, arch, loss_func=loss, metrics=all_metrics, n_out=20).to_fp16()
    # learn.lr_find()
    learn.fine_tune(epochs, 0.01)
    for dls in dls_gen:
        learn.dls = dls
        learn.fine_tune(epochs, 0.01)

After 20 epochs, it is better than training normally.

What would happen if we add progressive resizing?

## Using batch size 512:

In [16]:
prog_sizing([32, 64, 128, 224], epochs=10)  # min err: 0.024988
# It isn't traing very well when the size was big. probably needs smaller learning rate.

****
****************Size: 32****************
****


****
****************Size: 64****************
****


****
***************Size: 128****************
****


****
***************Size: 224****************
****


In [15]:
prog_sizing([64, 128, 224], 10)

****
****************Size: 64****************
****


****
***************Size: 128****************
****


****
***************Size: 224****************
****


Training with [32, 64, 128, 224] as image sizes reduced the error rate down to 0.024988. Let's try one more time. 

When it was training, I noticed the following:
- Loss got worse for couple epochs when image size was 224. I assume our learning rate was too big.
- When transitioning from size 32 to 64, loss starts out with a big value. Maybe transition slowly?

In [20]:
# DO it again for a 
prog_sizing([32, 64, 128, 224], epochs=10)

****************************************
****************Size: 32****************
****************************************


****************************************
****************Size: 64****************
****************************************


****************************************
***************Size: 128****************
****************************************


****************************************
***************Size: 224****************
****************************************


In [10]:
prog_sizing([32, 48, 64, 128, 224], epochs=10)

****************************************
****************Size: 32****************
****************************************


/usr/local/lib/python3.9/dist-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and will be removed in 0.15, please use 'weights' instead.
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and will be removed in 0.15. The current behavior is equivalent to passing `weights=ResNet18_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet18_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


****************************************
****************Size: 48****************
****************************************


****************************************
****************Size: 64****************
****************************************


****************************************
***************Size: 128****************
****************************************


****************************************
***************Size: 224****************
****************************************


## Using batch size 64:

When using progressive sizing, batch size can be 512 or 64. They almost give the same results.

### Using 10 epochs

Using 10 epochs doesn't seem to improve our score at all. It's just same as not using progressive sizing or multitask.

In [15]:
prog_sizing([32, 64, 128, 224], epochs=10)

****************************************
****************Size: 32****************
****************************************


****************************************
****************Size: 64****************
****************************************


****************************************
***************Size: 128****************
****************************************


****************************************
***************Size: 224****************
****************************************


In [16]:
prog_sizing([64, 128, 224], epochs=10)

****************************************
****************Size: 64****************
****************************************


****************************************
***************Size: 128****************
****************************************


****************************************
***************Size: 224****************
****************************************


In [17]:
prog_sizing([32, 48, 64, 128, 224], epochs=10)

****************************************
****************Size: 32****************
****************************************


****************************************
****************Size: 48****************
****************************************


****************************************
****************Size: 64****************
****************************************


****************************************
***************Size: 128****************
****************************************


****************************************
***************Size: 224****************
****************************************


### Using 6 epochs

Maybe we are training too much? Let's train less.

In [18]:
prog_sizing([32, 64, 128, 224], epochs=6)

****************************************
****************Size: 32****************
****************************************


****************************************
****************Size: 64****************
****************************************


****************************************
***************Size: 128****************
****************************************


****************************************
***************Size: 224****************
****************************************


In [19]:
prog_sizing([64, 128, 224], epochs=6)

****************************************
****************Size: 64****************
****************************************


****************************************
***************Size: 128****************
****************************************


****************************************
***************Size: 224****************
****************************************


In [20]:
prog_sizing([32, 48, 64, 128, 224], epochs=6)

****************************************
****************Size: 32****************
****************************************


****************************************
****************Size: 48****************
****************************************


****************************************
****************Size: 64****************
****************************************


****************************************
***************Size: 128****************
****************************************


****************************************
***************Size: 224****************
****************************************
