# Multitask

Recognizing variety -> recognizing disease

After changing head notebook, here is an easier way to do it.

In [1]:
from fastai.vision.all import *
from fastcore.parallel import *
path = Path()
trn_path = path/'train_images'

In [2]:
df = pd.read_csv('train.csv')
df.head()

image_id                  label variety  age
0  100330.jpg  bacterial_leaf_blight   ADT45   45
1  100365.jpg  bacterial_leaf_blight   ADT45   45
2  100382.jpg  bacterial_leaf_blight   ADT45   45
3  100632.jpg  bacterial_leaf_blight   ADT45   45
4  101918.jpg  bacterial_leaf_blight   ADT45   45

Turning DataLoaders into DataBlocks. We need to return 2 outputs, variety and disease.

In [3]:
arch = resnet18

In [4]:
img2variety = { r.image_id:r.variety for _,r in df.iterrows() }

In [5]:
def get_variety(p):
    "Turn path into image name"
    return img2variety[p.name]

## Customizing head

In [6]:
orig_lf = CrossEntropyLossFlat()

def disease_err(inp,disease,variety): return error_rate(inp[:,:10],disease)
def variety_err(inp,disease,variety): return error_rate(inp[:,10:],variety)
def disease_loss(inp,disease,variety): return orig_lf(inp[:,:10],disease)
def variety_loss(inp,disease,variety): return orig_lf(inp[:,10:],variety)
def loss(pred,disease,variety): return orig_lf(pred[:,:10],disease)+orig_lf(pred[:,10:],variety)
err_metrics = (disease_err,variety_err)
all_metrics = err_metrics+(disease_loss,variety_loss)

In [17]:
def get_dls(img_sizes):
    """Return the dataloaders"""
    for size in img_sizes:
        print('*' * 40)
        print(f'Size: {size}'.center(40, '*'))
        print('*' * 40)
        dblock = DataBlock(
            blocks=(ImageBlock, CategoryBlock, CategoryBlock),
            n_inp=1,                                             
            get_items=get_image_files,
            get_y=[parent_label, get_variety],
            splitter=RandomSplitter(seed=42),
            item_tfms=Resize(224, method='squish'),                
            batch_tfms=aug_transforms(size=size),
        )
        dls = dblock.dataloaders(trn_path, bs=512)
        yield dls

In [19]:
def prog_sizing(img_sizes, epochs=1):
    """Progressively use bigger images for training."""
    dls_gen = get_dls(img_sizes)
    dls = next(dls_gen)
    learn = vision_learner(dls, arch, loss_func=loss, metrics=all_metrics, n_out=20).to_fp16()
    # learn.lr_find()
    learn.fine_tune(epochs, 0.01)
    for dls in dls_gen:
        learn.dls = dls
        learn.fine_tune(epochs, 0.01)

In [9]:
# learn.fine_tune(20, 0.01) ## error: .033 

NameError: name 'learn' is not defined

After 20 epochs, it is better than training normally.

What would happen if we add progressive resizing?

In [16]:
prog_sizing([32, 64, 128, 224], epochs=10)  # min err: 0.024988
# It isn't traing very well when the size was big. probably needs smaller learning rate.

****
****************Size: 32****************
****


****
****************Size: 64****************
****


****
***************Size: 128****************
****


****
***************Size: 224****************
****


In [15]:
prog_sizing([64, 128, 224], 10)

****
****************Size: 64****************
****


****
***************Size: 128****************
****


****
***************Size: 224****************
****


Training with [32, 64, 128, 224] as image sizes reduced the error rate down to 0.024988. Let's try one more time. 

When it was training, I noticed the following:
- Loss got worse for couple epochs when image size was 224. I assume our learning rate was too big.
- When transitioning from size 32 to 64, loss starts out with a big value. Maybe transition slowly?

In [20]:
# DO it again for a 
prog_sizing([32, 64, 128, 224], epochs=10)

****************************************
****************Size: 32****************
****************************************


****************************************
****************Size: 64****************
****************************************


****************************************
***************Size: 128****************
****************************************


****************************************
***************Size: 224****************
****************************************


In [21]:
prog_sizing([32, 48, 64, 128, 224], epochs=10)

****************************************
****************Size: 32****************
****************************************


KeyboardInterrupt: 